name: Build gh pages site
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build site with dokka 🔧 
      run: |
        ./gradlew dokkaHtml
    - name: Deploy to gh pages 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # deploy branch
        FOLDER: build/dokka/html
        CLEAN: true # Automatically remove deleted files from the deploy branch