name: Build gh pages site
on:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build site with dokka 🔧 
      run: |
        npm install
        npm run build
    - name: Deploy to gh pages 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # deploy branch
        FOLDER: .
        CLEAN: true # Automatically remove deleted files from the deploy branch